# Logging Level
logging.level.root=INFO
logging.level.com.bridgelabz.addressbook=INFO

# Log to File only
logging.file.name=logs/prod.log

# Quiet console output in production
spring.main.banner-mode=off

# Log Format
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
