# Logging for Dev
logging.level.root=DEBUG
logging.level.com.bridgelabz.addressbook=DEBUG

# Log output location
logging.file.name=logs/dev.log

# Log format
logging.pattern.console=%d{HH:mm:ss} %-5level %logger{36} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n
