# Logging for Production
logging.level.root=INFO
logging.level.com.bridgelabz.addressbook=INFO

# Only log to file in prod
logging.file.name=logs/prod.log
spring.main.banner-mode=off

# Log format
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n
