# Logging Level
logging.level.root=DEBUG
logging.level.com.bridgelabz.addressbook=DEBUG

# Log to Console + File
logging.file.name=logs/dev.log

# Log Format
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
